# Generated by Django 3.2.5 on 2021-07-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('zubale_id', models.IntegerField()),
                ('determinante', models.IntegerField()),
                ('status', models.BooleanField()),
                ('cadena', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('cadena_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zub_id', models.IntegerField()),
                ('zubale_area', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('colonia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('url_google_maps', models.CharField(max_length=200)),
                ('fronterizo', models.BooleanField()),
                ('name_val', models.IntegerField()),
                ('lat_lon_val', models.IntegerField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='csv_manager.store')),
            ],
        ),
    ]
